# Configure ISC KEA
---

# - name: Check whether isc-dhcp-server.service is running
#   ansible.builtin.shell: "systemctl status isc-dhcp-server.service"
#   register: _isc_dhcp_status
#   failed_when:  False
#   changed_when: False
#   check_mode: no
#   when: domaenenliste is defined

# - name: Check whether isc-dhcp-server.service is enabled
#   ansible.builtin.shell: "systemctl is-enabled isc-dhcp-server.service"
#   register: _isc_dhcp_enabled
#   failed_when:  False
#   changed_when: False
#   check_mode: no
#   when: domaenenliste is defined

# - name: Stop isc-dhcp
#   ansible.builtin.service: name=isc-dhcp-server state=stopped
#   when:
#     - domaenenliste is defined
#     - _isc_dhcp_status.rc == 0

# - name: Disable isc-dhcp
#   ansible.builtin.service: name=isc-dhcp-server enabled=no
#   when:
#     - domaenenliste is defined
#     - _isc_dhcp_enabled.rc == 0

# - name: Enable kea-dhcp4.service
#   ansible.builtin.service: name=kea-dhcp4.service enabled=yes
#   when: domaenenliste is defined

# - name: Create /etc/kea directory
#   ansible.builtin.file: path=/etc/kea state=directory mode=0755
#   when: domaenenliste is defined

# - name: Create /var/kea directory
#   ansible.builtin.file: path=/var/kea state=directory mode=0755
#   when: domaenenliste is defined

- name: create /etc/kea/kea-dhcp4.conf
  ansible.builtin.template: src=keav4.conf.j2 dest=/etc/kea/kea-dhcp4.conf
  notify:
    - Restart kea-dhcp4 service
  when: domaenenliste is defined
