- name: Installiere nginx
  apt:
    name: "nginx"
    install_recommends: no
    state: present
  become: yes

- name: Installiere docker gpg key fürs ppa
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: install_docker
  become: yes

- name: Füge docker ppa hinzu
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: install_docker
  become: yes

- name: Installiere docker
  apt:
    name: "{{ packages }}"
    install_recommends: yes
    state: present
  vars:
    packages:
      - docker-ce
  when: install_docker
  become: yes
