# installierte batman-Version prüfen
- name: Prüfe installierte batman-adv-Version
  shell: |
    set -o pipefail
    modinfo -F version batman-adv | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?'
  args:
    executable: bash
  register: installed_batman_version
  when: batman.version is defined and batman.version
  changed_when: false
  check_mode: false

- name: Installierte Batman Version
  ansible.builtin.debug:
    var: installed_batman_version
#   when: installed_batman_version.stdout != batman.version

# - name: Installierte Batman Version
#   ansible.builtin.debug:
#     var: batman.version

# batman-adv und batctl aus Quellen bauen
- include_tasks: install-src.yml
  when: (batman.version is defined and batman.version != "kernel") and
        (installed_batman_version.stdout is defined and installed_batman_version.stdout != batman.version)

