# Remove builded ISC KEA
---
- name: Check whether builded version of kea-dhcp4.service is enabled
  ansible.builtin.shell: "systemctl is-enabled kea-dhcp4.service"
  register: _builded_kea_dhcp_enabled
  failed_when: false
  changed_when: false
  check_mode: false

- name: Stop builded kea-dhcp
  ansible.builtin.service:
    name: kea-dhcp4.service
    state: stopped
  when:
    - _builded_kea_dhcp_enabled.rc == 0

- name: Disable builded kea-dhcp
  ansible.builtin.service:
    name: kea-dhcp4.service
    enabled: false
  when:
    - _builded_kea_dhcp_enabled.rc == 0

- name: Remove systemd files
  ansible.builtin.file:
    path: "/lib/systemd/system/{{ item[:-3] }}"
    state: absent
  with_items:
    - kea-dhcp4.service.j2
    - kea-dhcp6.service.j2
    - kea-dhcp-ddns.service.j2
  notify:
    - Reload systemd
  when:
    - _builded_kea_dhcp_enabled.rc == 0

- name: Remove KEA binary
  ansible.builtin.file:
    path: "/usr/local/sbin/kea-dhcp4"
    state: absent
  when:
    - _builded_kea_dhcp_enabled.rc == 0

- name: Remove KEA folder
  ansible.builtin.file:
    path: "/srv/kea"
    state: absent
  when:
    - _builded_kea_dhcp_enabled.rc == 0

- name: Remove KEA config
  ansible.builtin.file:
    path: "/etc/kea/kea.conf"
    state: absent
  when:
    - _builded_kea_dhcp_enabled.rc == 0

- name: Remove KEA logrotate file
  ansible.builtin.file:
    path: "/etc/logrotate.d/kea-dhcp4"
    state: absent
  when:
    - _builded_kea_dhcp_enabled.rc == 0

- name: Remove PostgreSQL
  ansible.builtin.apt:
    name: ['postgresql-9.5']
    state: absent
      #  when:
      #    - _builded_kea_dhcp_enabled.rc == 0