# install bind9 service 
# ---
- name: Install bind9
  ansible.builtin.apt:
    pkg: bind9
    state: present

- name: Create folder for named logging
  ansible.builtin.file:
    path: /var/log/named/
    state: directory
    owner: bind
    group: root

- name: Create folder for named slave zonefiles
  ansible.builtin.file:
    path: /etc/bind/slave
    state: directory
    owner: bind
    group: root

- name: Deploy named.conf.log
  ansible.builtin.template:
    src: named.conf.log.j2
    dest: /etc/bind/named.conf.log
  notify:
    - Restart bind9

- name: Deploy named.conf.local
  ansible.builtin.template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local
  notify:
    - Restart bind9

- name: Deploy named.conf.options
  ansible.builtin.template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify:
    - Restart bind9

- name: Create named.conf.ffnet
  ansible.builtin.template: src=named.conf.ffnet.j2 dest=/etc/bind/named.conf.ffnet
  notify:
    - Restart bind9

- name: Create named.conf.tld
  ansible.builtin.template: src=named.conf.tld.j2 dest=/etc/bind/named.conf.tld
  notify:
    - Restart bind9
  when: is_external_nameserver is defined and is_external_nameserver

- name: Create named.conf
  ansible.builtin.template: src=named.conf.j2 dest=/etc/bind/named.conf
  notify:
    - Restart bind9

- name: Create own db file for each subdomaene
  ansible.builtin.template: src=db.ffnet.j2 dest=/etc/bind/db.domaene-{{item}}.ffnet
  notify:
    - Restart bind9
  with_items: "{{domaenenliste | default([])}}"
  when: domaenenliste is defined

- name: Create folder for bind9.service file
  ansible.builtin.file: path=/etc/systemd/system/bind9.service.d state=directory mode=0755

- name: Copy bind9.service
  ansible.builtin.copy: src=bind9.service dest=/etc/systemd/system/bind9.service.d/override.conf
  notify:
    - Restart bind9

- name: Deploy logrotate template file
  ansible.builtin.template:
    src: logrotate-bind.j2
    dest: /etc/logrotate.d/bind
  when:
    - domaenenliste is defined

