- name: restart nginx
  systemd:
    name: nginx.service
    state: restarted
  become: yes

- name: reload nginx
  systemd:
    name: nginx.service
    state: reloaded
  become: yes

- name: restart mariadb
  systemd:
    name: mariadb.service
    state: restarted
  become: yes

- name: restart php-fpm
  systemd:
    name: php7.4-fpm.service
    state: restarted
  become: yes

- name: restart redis-server
  systemd:
    name: redis-server.service
    state: restarted
  become: yes
