---
- name: Install dependencies for this role
  apt:
    name: ['gdebi-core', 'xz-utils', 'jq', 'bc']
    update_cache: yes
    state: present

- name: Download check-mk-agent
  get_url:
      url="{{ check_mk.deb }}"
      dest="/root/check_mk_agent.deb"

- name: Install checkmk package
  apt:
    deb: "/root/check_mk_agent.deb"

- name: checkmk localcheck cached directories
  file:
    path: /usr/lib/check_mk_agent/local/300
    recurse: yes
    state: directory
    mode: '0755'

- name: checkmk localcheck cached directories
  file:
    path: /usr/lib/check_mk_agent/local/600
    recurse: yes
    state: directory
    mode: '0755'

- name: dhtest Installation für den supernode-infra check
  block:
    - name: Install dependencies for make
      apt:
        name: ['build-essential']
        update_cache: yes
        state: present

    - name: Clone dhtest Repo
      git:
#        repo: https://github.com/saravana815/dhtest
        repo: https://git.ideenwerk.me/neanderfunk/dhtest
        dest: /opt/dhtest
        update: yes

    - name: make dhtest
      community.general.make:
        chdir: /opt/dhtest

    - name: installiere dhtest nach /usr/local/bin
      copy:
        src: /opt/dhtest/dhtest
        dest: /usr/local/bin/dhtest
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

- name: copy checkmk localcheck serverstatus
  copy: "src=serverstatus dest='/usr/lib/check_mk_agent/local/serverstatus' owner=root group=root mode='755'"
  when: checkmk_checks_serverstatus

- name: copy checkmk localcheck supernode
  copy: "src=supernode dest='/usr/lib/check_mk_agent/local/supernode' owner=root group=root mode='755'"
  when: checkmk_checks_supernode

- name: copy checkmk localcheck supernode-infra
  copy: "src=supernode-infra dest='/usr/lib/check_mk_agent/local/300/supernode-infra' owner=root group=root mode='755'"
  when: checkmk_checks_supernodeinfra

- name: copy checkmk localcheck updatestatus
  copy: "src=updatestatus dest='/usr/lib/check_mk_agent/local/600/updatestatus' owner=root group=root mode='755'"
  when: checkmk_checks_updatestatus
